### ISSUE TITLE
Feature Request: Add support for .NET 5.xx

### ISSUE THREAD

**Issue by Felipefpl** [abbodi1406/dotNetFx4xW7A#4]
Since there are support for win7 and .NET 5.xx it would be a good idea to have support for this.

**Comment by abbodi1406** [comment]
.NET 5 is Core not Framework

different product, different various components, and each new version is a full replacement, not patch updates

**Comment by Felipefpl** [comment]
i see, thanks for the reply and for the packages you make for us. :)
