### ISSUE TITLE
WinToolkit 1.7.0.15 integrate Language Pack Addon (dotNetFx48LP_x64_CHT.WA) Error

### ISSUE THREAD

**Issue by lgs2007m** [abbodi1406/dotNetFx4xW7A#5]
hi, abbodi1406

Recently，I customed my own Windows 7 SP1 Professional 64-bit ISO, using DISM to integrate updates before Jan 14, 2020. For the ESU updates, I used BypassESU-v11 on offline image integration. After that I got my ISO update to the August 10, 2021—KB5005088 (Monthly Rollup). Now, I want to integrate "_vcredist_x64_Win7.WA_", "_DirectX_June2010_x64.WA_", "_dotNetFx48_20210810_x64.WA_" and "_dotNetFx48LP_x64_CHS.WA_" into the ISO.

My computer system is Windows 11 Preview (Beta Channel) 21H2 (22000.176). I used WinToolkit_1.7.0.15 with NSudo_8.2, to integrate "_vcredist_x64_Win7.WA_", then reload the WinToolkit.exe to integrate the others. The  "dotNetFx48LP_x64_CHS.WA" was integrated at the end. But when "_dotNetFx48LP_x64_CHS.WA_" was  integrated, I found a error log in WinToolkit.

I verifyed the download hash, redid the process, but when "_dotNetFx48LP_x64_CHS.WA_" was  integrated, the error occurred. I can't solve the problem, because I can't understand the log. Can you help？

log file:
[Error_1.7.0_1x9DFB3E61BF77331E3412328828B50AEB_Ex06001694_frmAllInOne_zh-CN_114884.log](https://github.com/abbodi1406/dotNetFx4xW7A/files/7111211/Error_1.7.0_1x9DFB3E61BF77331E3412328828B50AEB_Ex06001694_frmAllInOne_zh-CN_114884.log)

**Comment by lgs2007m** [comment]
Sorry for disturbing you.
The reason for the error seems to be that the file path is too long.
I set Win Toolkit Temp Folder to C:\WinToolkit_Temp, Win Toolkit Mount Folder to C:\Mount. 
Run the Process again, no error occurred. It seems the problem is solved.

--------------------------------------------------------------------------
Part of the previous error log:
> ***BASIC***
> Error Copying Files
> 
> ***EXTENDED***
> Source: C:\Windows\WinToolkit_Temp\AddonTemp_63698D27BE660304C0D5B8AD2F56FD7D\Microsoft.NET\assembly\GAC_MSIL\System.ComponentModel.Composition.Registration.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\System.ComponentModel.Composition.Registration.resources.dll [30.11 KB]
> Dest: C:\WinToolkit_Mount_CE430B9ED1274D5203E1CC7383A4B8EE\Mount_29995\Windows\Microsoft.NET\assembly\GAC_MSIL\System.ComponentModel.Composition.Registration.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\System.ComponentModel.Composition.Registration.resources.dll
>  [102.29 GB]
> KeepOriginal: False
> Overwrite: True
> 
> ***EXCEPTION***
> 未能找到路径“C:\WinToolkit_Mount_CE430B9ED1274D5203E1CC7383A4B8EE\Mount_29995\Windows\Microsoft.NET\assembly\GAC_MSIL\System.ComponentModel.Composition.Registration.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\System.ComponentModel.Composition.Registration.resources.dll”的一部分。
> InnerException: 
> Source: mscorlib
> TargetSite: Void WinIOError(Int32, System.String)

**Comment by abbodi1406** [comment]
Glad it solved, thanks for notifying
P.S. i guess you can integrate all addons together with NSudo, no need to reload the WinToolkit.exe
