### ISSUE TITLE
DISM++ error

### ISSUE THREAD

**Issue by vadimlitvinenko87** [abbodi1406/dotNetFx4xW7A#8]
Only dotNetFx48_20240813_**x64**.WA
Вызывает сбой при открытии сессии DISM++, монтирование проходит без проблем. То есть старая версия плагина не вызывала такой проблемы. Как результат невозможно настроить обработанный образ с применением оследнего плагина, причем x86 версия такой проблемы не несет.
Causes a error when opening a DISM++ session, mounting goes without problems. Old version of the plugin did not cause such a problem. As a result, it is impossible to configure the processed image with latest WA plugin, and the x86 version does not have such a problem.

**Comment by abbodi1406** [comment]
Fixed
dotNetFx48_20240815_x64.WA

**Comment by vadimlitvinenko87** [comment]
Tested worked. Thanks.
